import { motion } from "framer-motion";
import Navbar from "@/components/Navbar";
import Footer from "@/components/Footer";
import { FileText, Building2, Shield, Eye, Cookie, Lock, UserCheck, Gavel, Mail, MapPin, Clock } from "lucide-react";

const Privacy = () => {
  const sections = [
    {
      icon: FileText,
      title: "1. GENERAL",
      items: [
        {
          label: "a) Electronic Record",
          content: "This document is an electronic record in terms of the Information Technology Act, 2000 and the Digital Personal Data Protection (DPDP) Act, 2023. This record is generated by a computer system and does not require physical or digital signatures.",
        },
        {
          label: "b) Proprietorship",
          content: 'The domain name www.jointlly.in ("Website") and the Jointlly Mobile Application are owned and operated by Jointlly Pvt Ltd, a company incorporated under the Companies Act, 2013, with its registered office in Bengaluru, Karnataka.',
        },
        {
          label: "c) Compliance Statement",
          content: "This Policy is published in accordance with Rule 3(1) of the Information Technology (Intermediaries Guidelines) Rules, 2011, and the mandates of the DPDP Act 2023, which require the publication of a Privacy Policy for access or usage of the Platform.",
        },
      ],
    },
    {
      icon: Shield,
      title: "2. DATA COLLECTION & CONSENT (DPDP ACT 2023)",
      items: [
        {
          label: "a) Affirmative Consent",
          content: 'By using the Website and providing information, the User provides clear, affirmative consent to Jointlly Pvt Ltd (the "Data Fiduciary") to collect and process personal data for the specific purposes outlined below.',
        },
        {
          label: "b) Information We Collect",
          content: "We collect verified information provided by you, including but not limited to:",
          details: [
            "Identity Data: Name, Phone Number, Email Address.",
            "Technical Property Data: Property ID (PID), Survey Number, Property Location (Geo-coordinates), Plot Size (sq. ft.), Road Width, and Project Requirements.",
            "Financial Data: Payment transaction references (Note: We do not store full credit/debit card numbers).",
          ],
        },
        {
          label: "c) Automatic Tracking",
          content: "We may automatically track information based on your IP address and behavior on the Website to improve safety and user experience. This includes browser information, device type, and URL navigation history to detect fraudulent bot activity.",
        },
      ],
    },
    {
      icon: Building2,
      title: "3. PURPOSE OF PROCESSING & DATA SHARING",
      items: [
        {
          label: "a) Matchmaking Infrastructure (Core Service)",
          content: "The primary purpose of data collection is to facilitate a high-precision discovery match between Landowners (\"Clients\") and Construction Professionals (\"Vendors\").",
        },
        {
          label: 'b) The "Rule of Five" (Strict Limitation)',
          content: "To protect User privacy while ensuring competitive choice, Jointlly will share the User's contact and property details with a maximum of five (5) matching professionals at any given time. Constraint: Your data is never broadcast to a public list or open directory.",
        },
        {
          label: "c) Extended Matching",
          content: "If the User requires more options after the initial batch, a manual request must be initiated by the User. This action constitutes a fresh consent event for sharing data with a second batch of five professionals.",
        },
        {
          label: "d) Commercial Enforcement & Revenue Protection",
          content: "For specific categories (Construction and Joint Development), Jointlly processes project status data to enforce the Anti-Circumvention Agreement. Usage: We track project milestones (e.g., \"Agreement Signed\") to calculate and recover the applicable Success Fee (0.75%). Legal Basis: Processing is necessary for the performance of a contract and recovery of legitimate dues.",
        },
        {
          label: "e) Legal Disclosure",
          content: "We may disclose personal information if required by law to respond to subpoenas, court orders, or official requests from the Data Protection Board of India.",
        },
      ],
    },
    {
      icon: Clock,
      title: "4. DATA LIFECYCLE BY CATEGORY",
      items: [
        {
          label: "a) Lead-Only Categories (Interiors & Renovation/Repaint)",
          content: "For these categories, data processing for \"Commercial Tracking\" ceases upon the successful \"Unlock\" of the lead. No long-term project status tracking is performed.",
        },
        {
          label: "b) Commission-Based Categories (Construction & JD)",
          content: "Data regarding the project status is retained and processed for 24 months or until the Success Fee is settled, whichever is later, to ensure compliance with the Anti-Circumvention terms.",
        },
      ],
    },
    {
      icon: Eye,
      title: "5. USER RIGHTS (DATA PRINCIPAL RIGHTS)",
      items: [
        {
          label: "Right to Access",
          content: "You may request a summary of the personal data being processed and the identities of the Data Processors (Builders) with whom it has been shared.",
        },
        {
          label: "Right to Correction",
          content: "You may request the correction of inaccurate or misleading data.",
        },
        {
          label: "Right to Erasure",
          content: "You may request the erasure of your data once the matchmaking purpose is fulfilled, subject to statutory retention laws (e.g., tax audits).",
        },
        {
          label: "Right to Withdraw Consent",
          content: 'You may withdraw your consent at any time via the "Consent Manager" in your account settings. Effect: Upon withdrawal, Jointlly will cease processing your data within 48 hours.',
        },
      ],
    },
    {
      icon: Lock,
      title: "6. SECURITY PRACTICES",
      items: [
        {
          label: "a) Encryption",
          content: "Jointlly Pvt Ltd employs industry-standard encryption (SSL/TLS) to protect data during transmission.",
        },
        {
          label: "b) Payment Security",
          content: "We do not store credit/debit card information. All payments are processed through RBI-authorized, PCI-DSS compliant third-party gateways (e.g., Razorpay/Stripe).",
        },
      ],
    },
    {
      icon: Cookie,
      title: "7. COOKIES",
      items: [
        {
          label: "Cookie Usage",
          content: "Jointlly uses cookies to analyze web page flow, measure promotional effectiveness, and promote trust. Some features are only available through the use of cookies. You may decline cookies through your browser settings, though this may limit platform functionality.",
        },
      ],
    },
    {
      icon: UserCheck,
      title: "8. GRIEVANCE REDRESSAL & DATA PROTECTION OFFICER",
      items: [
        {
          label: "Grievance Officer & DPO Details",
          content: "In accordance with the IT Act 2000 and DPDP Act 2023, the details of the Grievance Officer and Data Protection Officer (DPO) are provided below.",
          details: [
            "Name: Hemanth Murthy",
            "Designation: Grievance Officer & DPO",
            "Email: grievance@jointlly.in | dpo@jointlly.in",
            "Address: Banashankari, Bengaluru, 560061, Karnataka",
            "Response Timeline: Acknowledgment: Within 48 hours. Resolution: Within 30 days. Urgent Takedown (Identity Theft/Obscenity): Within 72 hours.",
          ],
        },
      ],
    },
    {
      icon: Gavel,
      title: "9. DISPUTE RESOLUTION & JURISDICTION",
      items: [
        {
          label: "a) Mediation",
          content: "Disputes regarding privacy or data use shall first be attempted to be resolved amicably within 30 days.",
        },
        {
          label: "b) Arbitration",
          content: "Unresolved disputes shall be referred to a sole arbitrator appointed by the Company. The seat of arbitration shall be Bengaluru, India, and the language shall be English.",
        },
        {
          label: "c) Jurisdiction",
          content: "This Policy is governed by the laws of India. The Courts at Bengaluru shall have exclusive jurisdiction over any disputes arising under this Policy.",
        },
      ],
    },
  ];

  return (
    <div className="min-h-screen bg-background overflow-x-hidden">
      <Navbar />
      <div className="absolute inset-0 bg-gradient-to-br from-emerald-50/70 via-green-50/60 to-teal-50/70" />
      <div className="absolute inset-0 jointlly-grid opacity-40" />
      <div className="relative z-10 py-12 sm:py-16 md:py-20">
        <div className="max-w-4xl mx-auto px-4 sm:px-6 lg:px-8">
          {/* Header */}
          <motion.div
            initial={{ opacity: 0, y: 20 }}
            animate={{ opacity: 1, y: 0 }}
            transition={{ duration: 0.5 }}
            className="text-center mb-8 sm:mb-12"
          >
            <h1 className="text-2xl sm:text-3xl md:text-4xl lg:text-5xl font-bold mb-3 sm:mb-4">
              <span className="text-gradient-primary">Privacy Policy</span>
            </h1>
            <p className="text-sm sm:text-base text-muted-foreground max-w-xl mx-auto">
              Jointlly Pvt Ltd
            </p>
            <p className="text-xs sm:text-sm text-muted-foreground mt-2">
              Effective Date: February 2026
            </p>
            <p className="text-xs sm:text-sm text-muted-foreground">
              Jurisdiction: India (DPDP Act 2023 Compliant)
            </p>
          </motion.div>

          {/* Privacy Policy Sections */}
          <div className="space-y-5 sm:space-y-8">
            {sections.map((section, sectionIndex) => {
              const Icon = section.icon;
              return (
                <motion.div
                  key={section.title}
                  initial={{ opacity: 0, y: 20 }}
                  animate={{ opacity: 1, y: 0 }}
                  transition={{ duration: 0.5, delay: sectionIndex * 0.1 }}
                  className="glass-card p-4 sm:p-5 md:p-6 lg:p-8"
                >
                  <div className="flex items-start gap-3 sm:gap-4 mb-4 sm:mb-6">
                    <div className="w-10 h-10 sm:w-12 sm:h-12 rounded-xl bg-gradient-to-br from-primary/20 to-accent/20 flex items-center justify-center flex-shrink-0">
                      <Icon className="w-5 h-5 sm:w-6 sm:h-6 text-primary" />
                    </div>
                    <h2 className="text-lg sm:text-xl md:text-2xl lg:text-3xl font-bold text-foreground flex-1 min-w-0">
                      {section.title}
                    </h2>
                  </div>

                  <div className="space-y-4 sm:space-y-6 ml-0 md:ml-16">
                    {section.items.map((item, itemIndex) => (
                      <div key={itemIndex} className="space-y-2">
                        <h3 className="font-semibold text-foreground text-lg">
                          {item.label}
                        </h3>
                        <p className="text-muted-foreground leading-relaxed">
                          {item.content}
                        </p>
                        {item.details && (
                          <div className="mt-3 space-y-2 pl-4 border-l-2 border-primary/20">
                            {item.details.map((detail, detailIndex) => (
                              <div key={detailIndex} className="flex items-start gap-2">
                                {detail.startsWith("Email:") && <Mail className="w-4 h-4 text-primary mt-1 flex-shrink-0" />}
                                {detail.startsWith("Address:") && <MapPin className="w-4 h-4 text-primary mt-1 flex-shrink-0" />}
                                {!detail.startsWith("Email:") && !detail.startsWith("Address:") && <span className="w-1.5 h-1.5 rounded-full bg-primary mt-2 flex-shrink-0" />}
                                <p className="text-muted-foreground">{detail}</p>
                              </div>
                            ))}
                          </div>
                        )}
                      </div>
                    ))}
                  </div>
                </motion.div>
              );
            })}
          </div>

          {/* Footer Note */}
          <motion.div
            initial={{ opacity: 0, y: 20 }}
            animate={{ opacity: 1, y: 0 }}
            transition={{ duration: 0.5, delay: 0.8 }}
            className="mt-12 p-6 rounded-xl bg-blue-500/10 border border-blue-500/20"
          >
            <p className="text-sm text-muted-foreground text-center">
              <strong className="text-foreground">Your Privacy Matters:</strong> We are committed to protecting your personal data in accordance with the DPDP Act 2023. For any privacy-related concerns or to exercise your rights, contact our Grievance Officer at grievance@jointlly.in or our Data Protection Officer at dpo@jointlly.in
            </p>
          </motion.div>
        </div>
      </div>
      <Footer />
    </div>
  );
};

export default Privacy;
