import { motion } from "framer-motion";
import Navbar from "@/components/Navbar";
import Footer from "@/components/Footer";
import { FileText, Scale, Users, Shield, CreditCard, Database, AlertTriangle, Gavel, Mail, MapPin, Lock } from "lucide-react";

const Terms = () => {
  const sections = [
    {
      icon: FileText,
      title: "1. GENERAL & NATURE OF SERVICE",
      items: [
        {
          label: "a) Electronic Record",
          content: "This document is an electronic record in terms of the Information Technology Act, 2000 and the rules made thereunder. This record is generated by a computer system and does not require physical or digital signatures.",
        },
        {
          label: "b) Intermediary Status",
          content: 'Jointlly ("the Website/App") is an Intermediary as defined under Section 2(1)(w) of the IT Act, 2000. We act solely as a technology platform to facilitate the discovery of real estate opportunities (Joint Development, Construction, Renovations, Interiors) by matching Landowners ("Clients") with Builders/Architects ("Vendors").',
        },
        {
          label: "c) Neutral Pipeline",
          content: 'You acknowledge that Jointlly is not a real estate developer, builder, or legal consultant. We do not provide "Professional Advice." Any data, FAR calculations, or matching results are generated algorithmically for informational purposes only.',
        },
      ],
    },
    {
      icon: Users,
      title: '2. THE MATCHMAKING SERVICE (THE "GATEKEEPER" PROTOCOL)',
      items: [
        {
          label: "a) Step 0: Algorithmic Curation",
          content: "Matches are not random. The \"Jointlly Intelligence Engine\" curates connections based on strict technical parameters, including:",
          details: [
            "Geographic Proximity: Vendors within a feasible radius (e.g., 10km).",
            "Technical Capacity: Road width suitability, plot size expertise, and project budget.",
            "Regulatory Status: RERA registration status for applicable project sizes.",
          ],
        },
        {
          label: 'b) The "Rule of Five" (Strict Limitation)',
          content: "To protect Client privacy and ensure high-intent connections, Jointlly facilitates the exchange of contact information between a maximum of five (5) matching Vendors and one (1) Client per active batch.",
        },
        {
          label: "c) No Endorsement",
          content: "The appearance of a Vendor on the platform does not constitute an endorsement or guarantee of their financial solvency, construction quality, or ethical conduct. The \"Verified\" badge refers strictly to the validation of identity documents (PAN/GST/RERA).",
        },
      ],
    },
    {
      icon: CreditCard,
      title: "3. COMMERCIAL TERMS: FEES, PAYMENTS & REFUNDS",
      items: [
        {
          label: "a) Client Platform Entry Fee (Strictly Access-Only)",
          content: "Clients (Landowners) are charged with a non-refundable \"Platform Entry Fee\" (₹99). Scope of Fee: This fee is strictly for access to the Jointlly proprietary interface and the usage of the digital project submission tools. Disclaimer: This fee is NOT a matchmaking guarantee. Paying this fee grants entry to the platform's ecosystem but does not guarantee that a builder will express interest, nor does it guarantee a specific number of matches or a successful project conversion.",
        },
        {
          label: "b) Vendor Gatekeeper Fee (Dynamic)",
          content: "Vendors pay a \"Gatekeeper Fee\" (ranging from ₹1,499 to ₹9,999 based on category) to unlock the full \"Client Dossier.\" This fee is for data access only and does not guarantee a successful contract conversion.",
        },
        {
          label: "c) Category-Specific Financial Models",
          content: "",
          details: [
            "Lead-Only Model (Interiors & Renovation/Repaint): The commercial relationship concludes upon the \"Unlock\" of the lead. No Success Fee is applicable.",
            "Commission Model (New Construction & Joint Development): High-value matches are subject to a Success Fee of 0.75% of the total project value or contract amount, payable upon the signing of the agreement.",
          ],
        },
        {
          label: "d) Refund Policy (Strict Audit)",
          content: "Fees are generally non-refundable. A Token Credit (Refund) is issued only if the lead data is proven to be \"Invalid\" (e.g., disconnected number, non-existent property) and reported within 48 hours of unlocking via the Dashboard. \"Negotiation Failure\" is not grounds for a refund.",
        },
      ],
    },
    {
      icon: Lock,
      title: "4. ANTI-CIRCUMVENTION & EXCLUSIVITY (CRITICAL)",
      items: [
        {
          label: "a) Non-Circumvention",
          content: "By accessing a \"Client Dossier\" via Jointlly, the Vendor agrees not to bypass the platform to conclude a transaction with the Client specifically to avoid paying the Success Fee.",
        },
        {
          label: "b) Exclusivity Period",
          content: "This non-circumvention obligation remains valid for a period of twenty-four (24) months from the date the lead was unlocked.",
        },
        {
          label: "c) Penalty for Breach",
          content: "In the event of a proven breach (i.e., concluding a deal with a Jointlly-introduced Client without notifying the platform), the Vendor shall be liable to pay Liquidated Damages equal to two times (2x) the applicable Success Fee, in addition to legal costs.",
        },
      ],
    },
    {
      icon: Scale,
      title: "5. RERA COMPLIANCE & USER OBLIGATIONS",
      items: [
        {
          label: "a) Mandatory RERA",
          content: "For projects exceeding 500 square meters or eight (8) units, the Vendor must provide a valid K-RERA Project Registration Number. Jointlly will automatically block matches for non-compliant large-scale projects.",
        },
        {
          label: "b) Agent Status",
          content: "Jointlly operates as a registered Real Estate Agent under Karnataka RERA.",
        },
        {
          label: "c) Client Due Diligence",
          content: "The User (Client) expressly agrees that it is their sole responsibility to conduct site visits, verify the Vendor's past projects, and check legal titles before entering into a contract. Jointlly is not a party to any contract signed between a Client and a Vendor.",
        },
      ],
    },
    {
      icon: Database,
      title: "6. DATA PRIVACY & DPDP ACT 2023",
      items: [
        {
          label: "a) Affirmative Consent",
          content: "By using Jointlly, you provide clear, affirmative consent for us to process your Property ID (PID), Location, and Contact details for the specific purpose of \"Matchmaking\".",
        },
        {
          label: "b) Purpose Limitation",
          content: "Data is processed strictly to facilitate discovery and, for Commission-Based categories, to track commercial milestones (e.g., Agreement Signing).",
        },
        {
          label: "c) Data Erasure & Withdrawal",
          content: "Users have the right to request erasure of their data once a match is concluded or to withdraw consent via the \"Consent Manager,\" subject to statutory retention requirements (e.g., Tax Audits, PMLA logs).",
        },
      ],
    },
    {
      icon: AlertTriangle,
      title: "7. LIMITATION OF LIABILITY",
      items: [
        {
          label: "a) Section 79 Protection",
          content: "As per Section 79 of the IT Act, Jointlly shall not be liable for any third-party information, data, or communication links made available by us.",
        },
        {
          label: "b) Abetment of Fraud",
          content: "Jointlly shall not be held liable for any scam, financial loss, delay, or construction defect caused by a Vendor. Our liability is strictly limited to the verification of the identity documents (PAN/GST/RERA) provided by the Vendor at the time of onboarding.",
        },
        {
          label: "c) Cap on Liability",
          content: "In any event, the total liability of Jointlly to a user shall not exceed the total fees paid by the user to the platform in the preceding three (3) months.",
        },
      ],
    },
    {
      icon: Shield,
      title: "8. GRIEVANCE REDRESSAL",
      items: [
        {
          label: "Contact Information",
          content: "In compliance with the Information Technology Rules, the Grievance Officer details are:",
          details: [
            "Name: Hemanth Murthy",
            "Email: grievance@jointlly.in",
            "Address: Banashankari, Bengaluru, 560061",
          ],
        },
      ],
    },
    {
      icon: Gavel,
      title: "9. DISPUTE RESOLUTION & JURISDICTION",
      items: [
        {
          label: "a) Mediation",
          content: "Any dispute shall first be attempted to be resolved via amicable Mediation within 30 days.",
        },
        {
          label: "b) Arbitration",
          content: "If mediation fails, the dispute shall be referred to a Sole Arbitrator appointed by Jointlly. The seat of arbitration shall be Bengaluru, Karnataka.",
        },
        {
          label: "c) Jurisdiction",
          content: "These terms are governed by the laws of India, and the courts of Bengaluru shall have exclusive jurisdiction.",
        },
      ],
    },
  ];

  return (
    <div className="min-h-screen bg-background overflow-x-hidden">
      <Navbar />
      <div className="absolute inset-0 bg-gradient-to-br from-emerald-50/70 via-green-50/60 to-teal-50/70" />
      <div className="absolute inset-0 jointlly-grid opacity-40" />
      <div className="relative z-10 py-12 sm:py-16 md:py-20">
        <div className="max-w-4xl mx-auto px-4 sm:px-6 lg:px-8">
          {/* Header */}
          <motion.div
            initial={{ opacity: 0, y: 20 }}
            animate={{ opacity: 1, y: 0 }}
            transition={{ duration: 0.5 }}
            className="text-center mb-8 sm:mb-12"
          >
            <h1 className="text-2xl sm:text-3xl md:text-4xl lg:text-5xl font-bold mb-3 sm:mb-4">
              <span className="text-gradient-primary">Terms of Use</span>
            </h1>
            <p className="text-sm sm:text-base text-muted-foreground max-w-xl mx-auto">
              Jointlly Pvt Ltd
            </p>
            <p className="text-xs sm:text-sm text-muted-foreground mt-2">
              Effective Date: February 2026
            </p>
            <p className="text-xs sm:text-sm text-muted-foreground">
              Jurisdiction: India (IT Act 2000 & DPDP Act 2023 Compliant)
            </p>
          </motion.div>

          {/* Terms Sections */}
          <div className="space-y-5 sm:space-y-8">
            {sections.map((section, sectionIndex) => {
              const Icon = section.icon;
              return (
                <motion.div
                  key={section.title}
                  initial={{ opacity: 0, y: 20 }}
                  animate={{ opacity: 1, y: 0 }}
                  transition={{ duration: 0.5, delay: sectionIndex * 0.1 }}
                  className="glass-card p-4 sm:p-5 md:p-6 lg:p-8"
                >
                  <div className="flex items-start gap-3 sm:gap-4 mb-4 sm:mb-6">
                    <div className="w-10 h-10 sm:w-12 sm:h-12 rounded-xl bg-gradient-to-br from-primary/20 to-accent/20 flex items-center justify-center flex-shrink-0">
                      <Icon className="w-5 h-5 sm:w-6 sm:h-6 text-primary" />
                    </div>
                    <h2 className="text-lg sm:text-xl md:text-2xl lg:text-3xl font-bold text-foreground flex-1 min-w-0">
                      {section.title}
                    </h2>
                  </div>

                  <div className="space-y-4 sm:space-y-6 ml-0 md:ml-16">
                    {section.items.map((item, itemIndex) => (
                      <div key={itemIndex} className="space-y-2">
                        <h3 className="font-semibold text-foreground text-lg">
                          {item.label}
                        </h3>
                        {item.content && (
                          <p className="text-muted-foreground leading-relaxed">
                            {item.content}
                          </p>
                        )}
                        {item.details && (
                          <div className={`space-y-2 pl-4 border-l-2 border-primary/20 ${item.content ? "mt-3" : ""}`}>
                            {item.details.map((detail, detailIndex) => (
                              <div key={detailIndex} className="flex items-start gap-2">
                                {detail.startsWith("Email:") && <Mail className="w-4 h-4 text-primary mt-1 flex-shrink-0" />}
                                {detail.startsWith("Address:") && <MapPin className="w-4 h-4 text-primary mt-1 flex-shrink-0" />}
                                {!detail.startsWith("Email:") && !detail.startsWith("Address:") && <span className="w-1.5 h-1.5 rounded-full bg-primary mt-2 flex-shrink-0" />}
                                <p className="text-muted-foreground">{detail}</p>
                              </div>
                            ))}
                          </div>
                        )}
                      </div>
                    ))}
                  </div>
                </motion.div>
              );
            })}
          </div>

          {/* Footer Note */}
          <motion.div
            initial={{ opacity: 0, y: 20 }}
            animate={{ opacity: 1, y: 0 }}
            transition={{ duration: 0.5, delay: 0.7 }}
            className="mt-12 p-6 rounded-xl bg-amber-500/10 border border-amber-500/20"
          >
            <p className="text-sm text-muted-foreground text-center">
              <strong className="text-foreground">Important:</strong> By using Jointlly's services, you acknowledge that you have read, understood, and agree to be bound by these Terms of Use. If you do not agree to these terms, please do not use our platform.
            </p>
          </motion.div>
        </div>
      </div>
      <Footer />
    </div>
  );
};

export default Terms;
